name: Dev Container Build and Push Image

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - ".github/.devcontainer/**"
      - ".github/workflows/devcontainer-build-and-push.yml"

jobs:
  build-and-push:
    uses: chenxiex/reusable_workflow/.github/workflows/devcontainer-build-and-push.yml@main
    permissions:
      contents: read
      packages: write